### ISSUE TITLE
Fix /gold.html

### ISSUE THREAD

**Issue by aaronryank** [pirate-ship/pirate-ship.github.io#11]
Ahoy, mateys! Th' /ahoy.html tavern be kind 'o lame but I don't be knowin' how to improve it. Could one 'o ye possibly help?

**Comment by jmmcarthur** [comment]
Isn't th' whole html file unnecessary 'n we could have a direct link to th' signup?

**Comment by nkalupahana** [comment]
Yeah, I agree with Jackson.

**Comment by aaronryank** [comment]
@nkalupahana @jmmcarthur I see your point, go ahead and delete it if you like or I could do so.
