### ISSUE TITLE
Improve the gold website

### ISSUE THREAD

**Issue by nmill** [pirate-ship/pirate-ship.github.io#2]
I will take care of this.

**Comment by nkalupahana** [comment]
Can you look at the redesign pull request first?

**Comment by nmill** [comment]
If anyone has suggestions to improve the gold website, let me know!

**Comment by aaronryank** [comment]
@nmill  Well there's an error on the page. When you scroll down it goes spazo.

**Comment by aaronryank** [comment]
@nmill We also might want a more HQ image because the one there is sort of blurry.

**Comment by aaronryank** [comment]
@nmill We should probably have a link going back to the main page, just for perfectionism...

**Comment by aaronryank** [comment]
@nmill And the 'Theme Song' doesn't link to anything.... that's all I've got right now.

**Comment by nmill** [comment]
OK, I'll look at that.

**Comment by aaronryank** [comment]
@nkalupahana any ideas about how to fix the image error?

**Comment by nmill** [comment]
I fixed it! I found a JavaScript file that makes the scrolling smooth.

**Comment by aaronryank** [comment]
@nmill Nice work!

**Comment by nmill** [comment]
Right now!
