### ISSUE TITLE
Old repository

### ISSUE THREAD

**Issue by aaronryank** [pirate-ship/pirate-ship.github.io#6]
Was the old `shockwave4488/gitworkshop` repository deleted? Or was I just kicked off?

**Comment by nkalupahana** [comment]
It's still there for me... 
https://github.com/shockwave4488/gitworkshop

**Comment by aaronryank** [comment]
Dang it! @dcobbley why did I get kicked off?

**Comment by dcobbley** [comment]
Coach Willie will discuss with you on Thursday.

-Dave

**Comment by aaronryank** [comment]
Did I do something wrong?

**Comment by aaronryank** [comment]
@dcobbley @nkalupahana @jmmcarthur I apologize for my unprofessional behavior on GitHub. I was carried away in the pirate business and forgot that this is a public website and we should be professional.

**Comment by aaronryank** [comment]
@dcobbley @nkalupahana @jmmcarthur I apologize for my unprofessional behavior on GitHub. I was carried away in the pirate business and forgot that this is a public website and we should be professional.
