### ISSUE TITLE
Retrieve pirate.c

### ISSUE THREAD

**Issue by aaronryank** [pirate-ship/pirate-ship.github.io#7]
Since I got removed from `gitworkshop` I would appreciate it if someone could retrieve the `pirate.c` files. Thanks

**Comment by jmmcarthur** [comment]
why were you removed

**Comment by aaronryank** [comment]
@jmmcarthur I don't know; trying to figure out

**Comment by nkalupahana** [comment]
#include <stdio.h>
#include <time.h>

void s_wait(int secs)
{
	int i = time(0);
	while ((i + secs) > time(0));
}

const char *pirate[] = {
    "Do what you want, 'cause a pirate be free,",
    "YOU ARE A PIRATE!",
    "Yar har, fiddle di dee,",
    "Being a pirate is alright to be,",
    "Do what you want 'cause a pirate be free,",
    "You are a pirate!",
    "You are a pirate!",
    "(crowd) Yay!",
    "We've got us a map, (a map!)",
    "To lead us to a hidden box,",
    "That's all locked up with locks! (with locks!)",
    "And buried deep away!",
    "We'll dig up the box, (the box!)",
    "We know it's full of precious booty!",
    "Burst open the locks!",
    "And then we'll say HOORAY!",
    "(girl's voice) Yar, har, fiddle di dee.",
    "If you love to sail the sea,",
    "You are a pirate!",
    "Weigh anchooor!",
    "Yar har, fiddle di dee,",
    "Being a pirate is alright with me!",
    "Do what you want 'cause a pirate is free,",
    "You are a pirate!",
    "Arr yarr, ahoy and avast,",
    "dinky-dink-dink-a-dinkadefast!",
    "Hang the black flag",
    "At the end of the mast!",
    "You are a pirate!",
    "Hahahahaha! (Yay!)",
    "We're sailing away (set sail!),",
    "Adventure awaits on every shore!",
    "We set sail and explore (ya-har!)",
    "And run and jump all day (Yay!)",
    "We float on our boat (the boat!)",
    "Until it's time to drop the anchor,",
    "Then hang up our coats (aye-aye!)",
    "Until we sail again!",
    "(girl's voice) Yar, har, fiddle di dee.",
    "If you love to sail the sea,",
    "You are a pirate!",
    "Laaaand ho!",
    "Yar har, fiddle di dee,",
    "Being a pirate is alright with me!",
    "Do what you want 'cause a pirate is free,",
    "You are a pirate!",
    "Yar har, wind at your back, lads,",
    "Wherever you go!",
    "(singing) Blue sky above and blue ocean below,",
    "You are a pirate!",
    "Hahahahahaha!",
    "You are a pirate!",
    "Heh-heh-heh-heh-heh-heh-heh."
};

int main()
{
    int i;
    for (i = 0; pirate[i]; i++) {
        printf("%s\n",pirate[i]);
        s_wait(1);
    }
    return 0;
}

**Comment by nkalupahana** [comment]
.file	"pirates.c"
	.text
	.globl	s_wait
	.type	s_wait, @function
s_wait:
.LFB0:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset 6, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register 6
	pushq	%rbx
	subq	$40, %rsp
	.cfi_offset 3, -24
	movl	%edi, -36(%rbp)
	movl	$0, %edi
	call	time
	movl	%eax, -20(%rbp)
	nop
.L2:
	movl	-36(%rbp), %eax
	movl	-20(%rbp), %edx
	addl	%edx, %eax
	movslq	%eax, %rbx
	movl	$0, %edi
	call	time
	cmpq	%rax, %rbx
	jg	.L2
	addq	$40, %rsp
	popq	%rbx
	popq	%rbp
	.cfi_def_cfa 7, 8
	ret
	.cfi_endproc
.LFE0:
	.size	s_wait, .-s_wait
	.globl	pirate
	.section	.rodata
	.align 8
.LC0:
	.string	"Do what you want, 'cause a pirate be free,"
.LC1:
	.string	"YOU ARE A PIRATE!"
.LC2:
	.string	"Yar har, fiddle di dee,"
	.align 8
.LC3:
	.string	"Being a pirate is alright to be,"
	.align 8
.LC4:
	.string	"Do what you want 'cause a pirate be free,"
.LC5:
	.string	"You are a pirate!"
.LC6:
	.string	"(crowd) Yay!"
.LC7:
	.string	"We've got us a map, (a map!)"
.LC8:
	.string	"To lead us to a hidden box,"
	.align 8
.LC9:
	.string	"That's all locked up with locks! (with locks!)"
.LC10:
	.string	"And buried deep away!"
	.align 8
.LC11:
	.string	"We'll dig up the box, (the box!)"
	.align 8
.LC12:
	.string	"We know it's full of precious booty!"
.LC13:
	.string	"Burst open the locks!"
.LC14:
	.string	"And then we'll say HOORAY!"
	.align 8
.LC15:
	.string	"(girl's voice) Yar, har, fiddle di dee."
.LC16:
	.string	"If you love to sail the sea,"
.LC17:
	.string	"Weigh anchooor!"
	.align 8
.LC18:
	.string	"Being a pirate is alright with me!"
	.align 8
.LC19:
	.string	"Do what you want 'cause a pirate is free,"
.LC20:
	.string	"Arr yarr, ahoy and avast,"
	.align 8
.LC21:
	.string	"dinky-dink-dink-a-dinkadefast!"
.LC22:
	.string	"Hang the black flag"
.LC23:
	.string	"At the end of the mast!"
.LC24:
	.string	"Hahahahaha! (Yay!)"
	.align 8
.LC25:
	.string	"We're sailing away (set sail!),"
	.align 8
.LC26:
	.string	"Adventure awaits on every shore!"
	.align 8
.LC27:
	.string	"We set sail and explore (ya-har!)"
	.align 8
.LC28:
	.string	"And run and jump all day (Yay!)"
	.align 8
.LC29:
	.string	"We float on our boat (the boat!)"
	.align 8
.LC30:
	.string	"Until its time to drop the anchor,,Then hang up our coats (aye-aye!)"
.LC31:
	.string	"Until we sail again!"
.LC32:
	.string	"Laaaand ho!"
	.align 8
.LC33:
	.string	"Yar har, wind at your back, lads,"
.LC34:
	.string	"Wherever you go!"
	.align 8
.LC35:
	.string	"(singing) Blue sky above and blue ocean below,"
.LC36:
	.string	"Hahahahahaha!"
.LC37:
	.string	"Heh-heh-heh-heh-heh-heh-heh."
	.data
	.align 32
	.type	pirate, @object
	.size	pirate, 416
pirate:
	.quad	.LC0
	.quad	.LC1
	.quad	.LC2
	.quad	.LC3
	.quad	.LC4
	.quad	.LC5
	.quad	.LC5
	.quad	.LC6
	.quad	.LC7
	.quad	.LC8
	.quad	.LC9
	.quad	.LC10
	.quad	.LC11
	.quad	.LC12
	.quad	.LC13
	.quad	.LC14
	.quad	.LC15
	.quad	.LC16
	.quad	.LC5
	.quad	.LC17
	.quad	.LC2
	.quad	.LC18
	.quad	.LC19
	.quad	.LC5
	.quad	.LC20
	.quad	.LC21
	.quad	.LC22
	.quad	.LC23
	.quad	.LC5
	.quad	.LC24
	.quad	.LC25
	.quad	.LC26
	.quad	.LC27
	.quad	.LC28
	.quad	.LC29
	.quad	.LC30
	.quad	.LC31
	.quad	.LC15
	.quad	.LC16
	.quad	.LC5
	.quad	.LC32
	.quad	.LC2
	.quad	.LC18
	.quad	.LC19
	.quad	.LC5
	.quad	.LC33
	.quad	.LC34
	.quad	.LC35
	.quad	.LC5
	.quad	.LC36
	.quad	.LC5
	.quad	.LC37
	.text
	.globl	main
	.type	main, @function
main:
.LFB1:
	.cfi_startproc
	pushq	%rbp
	.cfi_def_cfa_offset 16
	.cfi_offset 6, -16
	movq	%rsp, %rbp
	.cfi_def_cfa_register 6
	subq	$16, %rsp
	movl	$0, -4(%rbp)
	jmp	.L4
.L5:
	movl	-4(%rbp), %eax
	cltq
	movq	pirate(,%rax,8), %rax
	movq	%rax, %rdi
	call	puts
	movl	$1, %edi
	call	s_wait
	addl	$1, -4(%rbp)
.L4:
	movl	-4(%rbp), %eax
	cltq
	movq	pirate(,%rax,8), %rax
	testq	%rax, %rax
	jne	.L5
	movl	$0, %eax
	leave
	.cfi_def_cfa 7, 8
	ret
	.cfi_endproc
.LFE1:
	.size	main, .-main
	.ident	"GCC: (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4"
	.section	.note.GNU-stack,"",@progbits

**Comment by aaronryank** [comment]
@nkalupahana can you open a pull request to merge those?
